### ISSUE TITLE
a mistake in the "train.py"

### ISSUE THREAD

**Issue by 1996Wanglei** [jason9693/MusicTransformer-pytorch#3]
hello jason, 
thanks for your implementation! well job!
however, when i wanted to train the music transformer, i found that there is a mistake in the "train.py". 
i received this error:
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    metrics = metric_set(sample, batch_y)
  File "/home/mirlab2019/wanglei/MusicTransformer-pytorch/custom/metrics.py", line 69, in __call__
    return self.forward(input=input, target=target)
  File "/home/mirlab2019/wanglei/MusicTransformer-pytorch/custom/metrics.py", line 75, in forward
    for k, metric in self.metrics.items()}
  File "/home/mirlab2019/wanglei/MusicTransformer-pytorch/custom/metrics.py", line 75, in <dictcomp>
    for k, metric in self.metrics.items()}
AttributeError: 'tuple' object has no attribute 'to'

After further discovering,  i found that the reason is that a tuple is returned in the line 91, train.py.  And then the returned tuple is transferred to "metric_set()", however "metric_set()" should receive a tensor instead of a tuple.  Actually, adding a new variable to receive the returned attention weights could avoid the above error.

**Comment by mzliang-annie** [comment]
Do you know how to fix this in code?

**Comment by mzliang-annie** [comment]
if self.training:
                return fc.contiguous()
            else:
                return fc.contiguous(), [weight.contiguous() for weight in w]

Separate the original line in model.py to the above, just solve the issue

**Comment by adamoudad** [comment]
I made a PR #11  to fix this.
